--liquibase formatted sql
--changeset antoxakon:3  -- Формат: author:id
--comment: add subscriptions in docker


create table services
(
    id   bigserial
        primary key,
    name varchar(255) not null
        unique
);

create table users
(
    id         bigserial
        primary key,
    first_name varchar(255) not null,
    last_name  varchar(255) not null,
    login      varchar(255) not null
        unique
);

create table user_subscription
(
    sub_id     bigserial
        primary key,
    user_id    bigint not null
        references users,
    service_id bigint not null
        references services,
    id         bigint generated by default as identity
);
